### ISSUE TITLE
Lỗi hiển thị tiếng việt

### ISSUE THREAD

**Issue by NamNguyenPN** [Belmont-Gabriel/MIUI9-XML-Vietnamese#1]
Một số từ Tiếng Việt vẫn ko được thể hiện, mà thay vào đó là chữ Trung Quốc. cụ thể là chữ "À" nó thay bằng "R" và một số từ khác.  Mong bạn giúp mình sửa

**Comment by tuan1982** [comment]
Mình không hiểu ý. cụ thể hơn tý dc không

**Comment by NamNguyenPN** [comment]
À mấy bài nhạc ghi tên Tiếng Việt thì app Music và cả mấy app nhạc khác nó
ko thể hiện dc chữ tiếng việt mà bị thay thế bởi chữ Tàu.  Mình nghĩ chắc
nó bị lỗi tiếng việt cả hệ thống.  Đây là hình ảnh:



​

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-12-20 23:26 GMT+07:00 tuan1982 <notifications@github.com>:

**Comment by tuan1982** [comment]
Đây là lỗi font bạ à. không phải lỗi do TV gây nên, stop ở đây

**Comment by NamNguyenPN** [comment]
Mình xài font gốc của máy luôn mà bạn.  Nếu bạn biết cách sửa mong bạn chỉ
giúp mình


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-12-21 22:36 GMT+07:00 tuan1982 <notifications@github.com>:
